In [117]:
import pandas as pd
import statistics

df = pd.read_csv('/content/bhp (1).csv')

#Remove outliers using percentile technique first. Use [0.001, 0.999] for lower and upper bound percentiles

upper_limit_new = df['price_per_sqft'].quantile(0.999)
lower_limit_new = df['price_per_sqft'].quantile(0.001)

print("Upper Limit: ", upper_limit_new)
print("Lower Limit: ", lower_limit_new)

#New dataframe 'no_outliers' excluding the percentile ouliers below 0.001 and above 0.999

no_outliers = df[(df['price_per_sqft'] < upper_limit_new) & (df['price_per_sqft'] > lower_limit_new)]

no_outliers

Upper Limit:  50959.36200000098
Lower Limit:  1366.184

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250
...,...,...,...,...,...,...,...
13195,Whitefield,5 Bedroom,3453.0,4.0,231.00,5,6689
13196,other,4 BHK,3600.0,5.0,400.00,4,11111
13197,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,60.00,2,5258
13198,Padmanabhanagar,4 BHK,4689.0,4.0,488.00,4,10407
13199,Doddathoguru,1 BHK,550.0,1.0,17.00,1,3090

In [113]:
#On the 'no_outliers' dataframe, use 4 standard deviation to remove outliers

#clarify the minimum and maximum limits
min_limit = no_outliers['price_per_sqft'].mean() - 4 * no_outliers['price_per_sqft'].std()
max_limit = no_outliers['price_per_sqft'].mean() + 4 * no_outliers['price_per_sqft'].std()

max_limit, min_limit

no_outliers[(no_outliers['price_per_sqft'] < max_limit) & (no_outliers['price_per_sqft'] > min_limit)]

,location,size,total_sqft,bath,price,bhk,price_per_sqft,zscore
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699,-0.715923
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615,-0.494722
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305,-0.569583
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245,-0.101099
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250,-0.582864
...,...,...,...,...,...,...,...,...
13195,Whitefield,5 Bedroom,3453.0,4.0,231.00,5,6689,0.006121
13196,other,4 BHK,3600.0,5.0,400.00,4,11111,1.073973
13197,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,60.00,2,5258,-0.339446
13198,Padmanabhanagar,4 BHK,4689.0,4.0,488.00,4,10407,0.903967
13199,Doddathoguru,1 BHK,550.0,1.0,17.00,1,3090,-0.862989

In [114]:
#Use zscore of 4 to remove outliers. This is quite similar to step (3) and you will get exact same result

no_outliers['zscore'] = (no_outliers.price_per_sqft - no_outliers.price_per_sqft.mean())/no_outliers.price_per_sqft.std()

no_outliers[(no_outliers['zscore'] < 4) & (no_outliers['zscore'] > -4)]

/tmp/ipykernel_3070/962175037.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_outliers['zscore'] = (no_outliers.price_per_sqft - no_outliers.price_per_sqft.mean())/no_outliers.price_per_sqft.std()

,location,size,total_sqft,bath,price,bhk,price_per_sqft,zscore
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699,-0.715923
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615,-0.494722
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305,-0.569583
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245,-0.101099
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250,-0.582864
...,...,...,...,...,...,...,...,...
13195,Whitefield,5 Bedroom,3453.0,4.0,231.00,5,6689,0.006121
13196,other,4 BHK,3600.0,5.0,400.00,4,11111,1.073973
13197,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,60.00,2,5258,-0.339446
13198,Padmanabhanagar,4 BHK,4689.0,4.0,488.00,4,10407,0.903967
13199,Doddathoguru,1 BHK,550.0,1.0,17.00,1,3090,-0.862989